config/routes.rb
Rails.application.routes.draw do
  get 'home/index'

  get 'home/about'

  get 'home/contact'

  root 'home#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

  def about
  end

  def contact
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/about.html.erb
<div class="header">
  <h2>What We Do</h2>
     
  <p>Founded in 2011, The Urban Canopy is comprised of five main programs which include our IFarm (indoor farm), OFarm (outdoor farm), LUCSA (Local Unified Community Supported Agriculture), Farmers Markets, and Compost Club.

We are pioneering the local food cycle to create a more sustainable and equitable food system in Chicago. We are growers, distributors, composters, and community partners who seek to directly impact our city for the better. We strive to make local healthy produce more accessible to all, reduce the miles fresh food travels, and create and maintain local jobs. Use the sidebar links to learn more about our programs or get in touch. </p>
</div>

<div class="row">
  <div class="column" style="background-color:#aaa;">Column</div>
  <div class="column" style="background-color:#bbb;">Column</div>
  <div class="column" style="background-color:#ccc;">Column</div>
</div>

<div class="footer">
  <p>Footer
  <%=link_to "Home", home_index_path%><br>
<%=link_to "Contact", home_contact_path%><br></p>
</div>

app/views/home/contact.html.erb
<h1>Contact Us</h1>
<p>Find me in app/views/home/contact.html.erb</p>
<%=link_to "Home", home_index_path%><br>
<%=link_to "About", home_about_path%><br>

app/views/home/index.html.erb
<div class="header">
    <h2>THE URBAN CANOPY</h2>
    <p></p>
</div>
<body>
<div class="row">
    <div class="column" style="background-color:#aaa;">
        <%=link_to "About", home_about_path%>
    </div>
    <div class="column" style="background-color:#bbb;">
        <%=link_to "Contact", home_contact_path%>
    </div>
    <div class="column" style="background-color:#ccc;">Column</div>
</div>
<div class="footer">
    <p>Footer</p>
</div>
</body>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>canopy</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>